language: node_js

node_js:
  - stable

services:
  - docker

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: 'Tests'
      name: 'Unit Tests'
      env:
        - CI=true
      script:
        - yarn
        - yarn test
    - script: yarn test --coverage
      name: 'Coverage Report'
      before_script:
        - touch .coveralls.yml
        - echo "repo_token: uhk77XiXtPe7mX5DbCER5DT27bWLK9hcM" > .coveralls.yml
      after_script:
        - cat coverage/lcov.info | coveralls
