language: node_js

node_js:
  - stable

services:
  - docker

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: Tests
      name: Unit Tests
      script:
        - docker build -t test-frontend -f frontend/Dockerfile-test frontend
        - docker run test-frontend
