language: node_js

node_js:
  - stable

services:
  - docker

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: 'Tests'
      name: 'Unit Tests'
      env:
        - CI=true
      script:
        - yarn
        - yarn test --passWithNoTests
    - before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
    - script: yarn test --coverage --passWithNoTests
      name: ''
    - after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
