language: node_js
services:
  - docker

jobs:
include:
    - stage: "Tests"
    name: "Unit Tests"
    script: docker build -t test-frontend -f frontend/Dockerfile-test frontend
    script: docker run test-frontend
   